# .github/workflows/docker-image.yml

name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # If you need to push to a registry like Docker Hub, uncomment and configure the login step:
    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and export to Docker (loads image into local Docker daemon)
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true # Load the image into the local Docker daemon
        tags: nostria/nostria-status:latest # Use your Docker Hub username or org
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # Optional: Add steps here to push the image to a registry
    # Example for pushing:
    # - name: Build and push to Docker Hub
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     push: true
    #     tags: your-dockerhub-username/nostria-status:latest # Replace with your actual tag
    #     cache-from: type=gha
    #     cache-to: type=gha,mode=max

    # Optional: Add steps here to run tests on the built image
